### ISSUE TITLE
Error running production build

### ISSUE THREAD

**Issue by justinmoon** [autsakorn/nextjs-antd-custom#1]
Running in development work fine with `yarn dev` ... but trying to run a production build fails:

```
$ yarn build
...
$ yarn start
yarn run v1.19.1
$ next start
> Ready on http://localhost:3000
ch/home/justin/dev/experiments/nextjs-antd-custom/node_modules/antd/lib/style/index.less:1
@import './themes/index';
^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/justin/dev/experiments/nextjs-antd-custom/node_modules/antd/lib/card/style/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

**Comment by LuisRodriguezLD** [comment]
same here
